// FontAwesome.swift
//
// Copyright (c) 2014-2015 Thi Doan
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.

import UIKit
import CoreText

private class FontLoader {
    class func loadFont(name: String) {
        let bundle = NSBundle(forClass: FontLoader.self)
        var fontURL = NSURL()
        let identifier = bundle.bundleIdentifier

        if identifier?.hasPrefix("org.cocoapods") == true {
            // If this framework is added using CocoaPods, resources is placed under a subdirectory
            fontURL = bundle.URLForResource(name, withExtension: "otf", subdirectory: "FontAwesome.swift.bundle")!
        } else {
            fontURL = bundle.URLForResource(name, withExtension: "otf")!
        }

        let data = NSData(contentsOfURL: fontURL)!

        let provider = CGDataProviderCreateWithCFData(data)
        let font = CGFontCreateWithDataProvider(provider)!

        var error: Unmanaged<CFError>?
        if !CTFontManagerRegisterGraphicsFont(font, &error) {
            let errorDescription: CFStringRef = CFErrorCopyDescription(error!.takeUnretainedValue())
            let nsError = error!.takeUnretainedValue() as AnyObject as! NSError
            NSException(name: NSInternalInconsistencyException, reason: errorDescription as String, userInfo: [NSUnderlyingErrorKey: nsError]).raise()
        }
    }
}

public extension UIFont {
    public class func fontAwesomeOfSize(fontSize: CGFloat) -> UIFont {
        struct Static {
            static var onceToken : dispatch_once_t = 0
        }

        let name = "FontAwesome"
        if (UIFont.fontNamesForFamilyName(name).count == 0) {
            dispatch_once(&Static.onceToken) {
                FontLoader.loadFont(name)
            }
        }

        return UIFont(name: name, size: fontSize)!
    }
}

public extension String {
    public static func fontAwesomeIconWithName(name: FontAwesome) -> String {
        return name.rawValue.substringToIndex(advance(name.rawValue.startIndex, 1))
    }
}

public extension UIImage {
    public static func fontAwesomeIconWithName(name: FontAwesome, textColor: UIColor, size: CGSize) -> UIImage {
        let paragraph = NSMutableParagraphStyle()
        paragraph.lineBreakMode = NSLineBreakMode.ByWordWrapping
        paragraph.alignment = .Center
        let attributedString = NSAttributedString(string: String.fontAwesomeIconWithName(name) as String, attributes: [NSFontAttributeName: UIFont.fontAwesomeOfSize(24.0), NSForegroundColorAttributeName: textColor, NSParagraphStyleAttributeName:paragraph])
        let size = sizeOfAttributeString(attributedString, size.width)
        UIGraphicsBeginImageContextWithOptions(size, false , 0.0)
        attributedString.drawInRect(CGRectMake(0, 0, size.width, size.height))
        let image = UIGraphicsGetImageFromCurrentImageContext()
        UIGraphicsEndImageContext()
        return image
    }
}

func sizeOfAttributeString(str: NSAttributedString, maxWidth: CGFloat) -> CGSize {
    let size = str.boundingRectWithSize(CGSizeMake(maxWidth, 1000), options:(NSStringDrawingOptions.UsesLineFragmentOrigin), context:nil).size
    return size
}

public extension String {
    public static func fontAwesomeIconWithCode(code: String) -> String? {
        let dict = [
            "fa-bank" : "\u{f19c}",
            "fa-bar-chart-o" : "\u{f080}",
            "fa-battery-0" : "\u{f244}",
            "fa-battery-1" : "\u{f243}",
            "fa-battery-2" : "\u{f242}",
            "fa-battery-3" : "\u{f241}",
            "fa-battery-4" : "\u{f240}",
            "fa-bitcoin" : "\u{f15a}",
            "fa-cab" : "\u{f1ba}",
            "fa-chain" : "\u{f0c1}",
            "fa-close" : "\u{f00d}",
            "fa-cny" : "\u{f157}",
            "fa-copy" : "\u{f0c5}",
            "fa-cut" : "\u{f0c4}",
            "fa-dashboard" : "\u{f0e4}",
            "fa-dedent" : "\u{f03b}",
            "fa-dollar" : "\u{f155}",
            "fa-edit" : "\u{f044}",
            "fa-euro" : "\u{f153}",
            "fa-facebook-f" : "\u{f09a}",
            "fa-feed" : "\u{f09e}",
            "fa-file-movie-o" : "\u{f1c8}",
            "fa-file-photo-o" : "\u{f1c5}",
            "fa-file-picture-o" : "\u{f1c5}",
            "fa-file-sound-o" : "\u{f1c7}",
            "fa-file-zip-o" : "\u{f1c6}",
            "fa-flash" : "\u{f0e7}",
            "fa-ge" : "\u{f1d1}",
            "fa-gear" : "\u{f013}",
            "fa-gears" : "\u{f085}",
            "fa-gittip" : "\u{f184}",
            "fa-group" : "\u{f0c0}",
            "fa-hand-grab-o" : "\u{f255}",
            "fa-hand-stop-o" : "\u{f256}",
            "fa-hotel" : "\u{f236}",
            "fa-hourglass-1" : "\u{f251}",
            "fa-hourglass-2" : "\u{f252}",
            "fa-hourglass-3" : "\u{f253}",
            "fa-image" : "\u{f03e}",
            "fa-institution" : "\u{f19c}",
            "fa-intersex" : "\u{f224}",
            "fa-legal" : "\u{f0e3}",
            "fa-life-bouy" : "\u{f1cd}",
            "fa-life-buoy" : "\u{f1cd}",
            "fa-life-saver" : "\u{f1cd}",
            "fa-mail-forward" : "\u{f064}",
            "fa-mail-reply" : "\u{f112}",
            "fa-mail-reply-all" : "\u{f122}",
            "fa-mobile-phone" : "\u{f10b}",
            "fa-mortar-board" : "\u{f19d}",
            "fa-navicon" : "\u{f0c9}",
            "fa-paste" : "\u{f0ea}",
            "fa-photo" : "\u{f03e}",
            "fa-ra" : "\u{f1d0}",
            "fa-remove" : "\u{f00d}",
            "fa-reorder" : "\u{f0c9}",
            "fa-rmb" : "\u{f157}",
            "fa-rotate-left" : "\u{f0e2}",
            "fa-rotate-right" : "\u{f01e}",
            "fa-rouble" : "\u{f158}",
            "fa-ruble" : "\u{f158}",
            "fa-rupee" : "\u{f156}",
            "fa-save" : "\u{f0c7}",
            "fa-send" : "\u{f1d8}",
            "fa-send-o" : "\u{f1d9}",
            "fa-shekel" : "\u{f20b}",
            "fa-sheqel" : "\u{f20b}",
            "fa-soccer-ball-o" : "\u{f1e3}",
            "fa-sort-down" : "\u{f0dd}",
            "fa-sort-up" : "\u{f0de}",
            "fa-star-half-empty" : "\u{f123}",
            "fa-star-half-full" : "\u{f123}",
            "fa-support" : "\u{f1cd}",
            "fa-toggle-down" : "\u{f150}",
            "fa-toggle-left" : "\u{f191}",
            "fa-toggle-right" : "\u{f152}",
            "fa-toggle-up" : "\u{f151}",
            "fa-turkish-lira" : "\u{f195}",
            "fa-tv" : "\u{f26c}",
            "fa-unlink" : "\u{f127}",
            "fa-unsorted" : "\u{f0dc}",
            "fa-warning" : "\u{f071}",
            "fa-wechat" : "\u{f1d7}",
            "fa-won" : "\u{f159}",
            "fa-yc" : "\u{f23b}",
            "fa-yc-square" : "\u{f1d4}",
            "fa-yen" : "\u{f157}",
            "fa-y-combinator-square" : "\u{f1d4}",
            "fa-glass" : "\u{f000}",
            "fa-music" : "\u{f001}",
            "fa-search" : "\u{f002}",
            "fa-envelope-o" : "\u{f003}",
            "fa-heart" : "\u{f004}",
            "fa-star" : "\u{f005}",
            "fa-star-o" : "\u{f006}",
            "fa-user" : "\u{f007}",
            "fa-film" : "\u{f008}",
            "fa-th-large" : "\u{f009}",
            "fa-th" : "\u{f00a}",
            "fa-th-list" : "\u{f00b}",
            "fa-check" : "\u{f00c}",
            "fa-times" : "\u{f00d}",
            "fa-search-plus" : "\u{f00e}",
            "fa-search-minus" : "\u{f010}",
            "fa-power-off" : "\u{f011}",
            "fa-signal" : "\u{f012}",
            "fa-cog" : "\u{f013}",
            "fa-trash-o" : "\u{f014}",
            "fa-home" : "\u{f015}",
            "fa-file-o" : "\u{f016}",
            "fa-clock-o" : "\u{f017}",
            "fa-road" : "\u{f018}",
            "fa-download" : "\u{f019}",
            "fa-arrow-circle-o-down" : "\u{f01a}",
            "fa-arrow-circle-o-up" : "\u{f01b}",
            "fa-inbox" : "\u{f01c}",
            "fa-play-circle-o" : "\u{f01d}",
            "fa-repeat" : "\u{f01e}",
            "fa-refresh" : "\u{f021}",
            "fa-list-alt" : "\u{f022}",
            "fa-lock" : "\u{f023}",
            "fa-flag" : "\u{f024}",
            "fa-headphones" : "\u{f025}",
            "fa-volume-off" : "\u{f026}",
            "fa-volume-down" : "\u{f027}",
            "fa-volume-up" : "\u{f028}",
            "fa-qrcode" : "\u{f029}",
            "fa-barcode" : "\u{f02a}",
            "fa-tag" : "\u{f02b}",
            "fa-tags" : "\u{f02c}",
            "fa-book" : "\u{f02d}",
            "fa-bookmark" : "\u{f02e}",
            "fa-print" : "\u{f02f}",
            "fa-camera" : "\u{f030}",
            "fa-font" : "\u{f031}",
            "fa-bold" : "\u{f032}",
            "fa-italic" : "\u{f033}",
            "fa-text-height" : "\u{f034}",
            "fa-text-width" : "\u{f035}",
            "fa-align-left" : "\u{f036}",
            "fa-align-center" : "\u{f037}",
            "fa-align-right" : "\u{f038}",
            "fa-align-justify" : "\u{f039}",
            "fa-list" : "\u{f03a}",
            "fa-outdent" : "\u{f03b}",
            "fa-indent" : "\u{f03c}",
            "fa-video-camera" : "\u{f03d}",
            "fa-picture-o" : "\u{f03e}",
            "fa-pencil" : "\u{f040}",
            "fa-map-marker" : "\u{f041}",
            "fa-adjust" : "\u{f042}",
            "fa-tint" : "\u{f043}",
            "fa-pencil-square-o" : "\u{f044}",
            "fa-share-square-o" : "\u{f045}",
            "fa-check-square-o" : "\u{f046}",
            "fa-arrows" : "\u{f047}",
            "fa-step-backward" : "\u{f048}",
            "fa-fast-backward" : "\u{f049}",
            "fa-backward" : "\u{f04a}",
            "fa-play" : "\u{f04b}",
            "fa-pause" : "\u{f04c}",
            "fa-stop" : "\u{f04d}",
            "fa-forward" : "\u{f04e}",
            "fa-fast-forward" : "\u{f050}",
            "fa-step-forward" : "\u{f051}",
            "fa-eject" : "\u{f052}",
            "fa-chevron-left" : "\u{f053}",
            "fa-chevron-right" : "\u{f054}",
            "fa-plus-circle" : "\u{f055}",
            "fa-minus-circle" : "\u{f056}",
            "fa-times-circle" : "\u{f057}",
            "fa-check-circle" : "\u{f058}",
            "fa-question-circle" : "\u{f059}",
            "fa-info-circle" : "\u{f05a}",
            "fa-crosshairs" : "\u{f05b}",
            "fa-times-circle-o" : "\u{f05c}",
            "fa-check-circle-o" : "\u{f05d}",
            "fa-ban" : "\u{f05e}",
            "fa-arrow-left" : "\u{f060}",
            "fa-arrow-right" : "\u{f061}",
            "fa-arrow-up" : "\u{f062}",
            "fa-arrow-down" : "\u{f063}",
            "fa-share" : "\u{f064}",
            "fa-expand" : "\u{f065}",
            "fa-compress" : "\u{f066}",
            "fa-plus" : "\u{f067}",
            "fa-minus" : "\u{f068}",
            "fa-asterisk" : "\u{f069}",
            "fa-exclamation-circle" : "\u{f06a}",
            "fa-gift" : "\u{f06b}",
            "fa-leaf" : "\u{f06c}",
            "fa-fire" : "\u{f06d}",
            "fa-eye" : "\u{f06e}",
            "fa-eye-slash" : "\u{f070}",
            "fa-exclamation-triangle" : "\u{f071}",
            "fa-plane" : "\u{f072}",
            "fa-calendar" : "\u{f073}",
            "fa-random" : "\u{f074}",
            "fa-comment" : "\u{f075}",
            "fa-magnet" : "\u{f076}",
            "fa-chevron-up" : "\u{f077}",
            "fa-chevron-down" : "\u{f078}",
            "fa-retweet" : "\u{f079}",
            "fa-shopping-cart" : "\u{f07a}",
            "fa-folder" : "\u{f07b}",
            "fa-folder-open" : "\u{f07c}",
            "fa-arrows-v" : "\u{f07d}",
            "fa-arrows-h" : "\u{f07e}",
            "fa-bar-chart" : "\u{f080}",
            "fa-twitter-square" : "\u{f081}",
            "fa-facebook-square" : "\u{f082}",
            "fa-camera-retro" : "\u{f083}",
            "fa-key" : "\u{f084}",
            "fa-cogs" : "\u{f085}",
            "fa-comments" : "\u{f086}",
            "fa-thumbs-o-up" : "\u{f087}",
            "fa-thumbs-o-down" : "\u{f088}",
            "fa-star-half" : "\u{f089}",
            "fa-heart-o" : "\u{f08a}",
            "fa-sign-out" : "\u{f08b}",
            "fa-linkedin-square" : "\u{f08c}",
            "fa-thumb-tack" : "\u{f08d}",
            "fa-external-link" : "\u{f08e}",
            "fa-sign-in" : "\u{f090}",
            "fa-trophy" : "\u{f091}",
            "fa-github-square" : "\u{f092}",
            "fa-upload" : "\u{f093}",
            "fa-lemon-o" : "\u{f094}",
            "fa-phone" : "\u{f095}",
            "fa-square-o" : "\u{f096}",
            "fa-bookmark-o" : "\u{f097}",
            "fa-phone-square" : "\u{f098}",
            "fa-twitter" : "\u{f099}",
            "fa-facebook" : "\u{f09a}",
            "fa-github" : "\u{f09b}",
            "fa-unlock" : "\u{f09c}",
            "fa-credit-card" : "\u{f09d}",
            "fa-rss" : "\u{f09e}",
            "fa-hdd-o" : "\u{f0a0}",
            "fa-bullhorn" : "\u{f0a1}",
            "fa-bell-o" : "\u{f0a2}",
            "fa-certificate" : "\u{f0a3}",
            "fa-hand-o-right" : "\u{f0a4}",
            "fa-hand-o-left" : "\u{f0a5}",
            "fa-hand-o-up" : "\u{f0a6}",
            "fa-hand-o-down" : "\u{f0a7}",
            "fa-arrow-circle-left" : "\u{f0a8}",
            "fa-arrow-circle-right" : "\u{f0a9}",
            "fa-arrow-circle-up" : "\u{f0aa}",
            "fa-arrow-circle-down" : "\u{f0ab}",
            "fa-globe" : "\u{f0ac}",
            "fa-wrench" : "\u{f0ad}",
            "fa-tasks" : "\u{f0ae}",
            "fa-filter" : "\u{f0b0}",
            "fa-briefcase" : "\u{f0b1}",
            "fa-arrows-alt" : "\u{f0b2}",
            "fa-users" : "\u{f0c0}",
            "fa-link" : "\u{f0c1}",
            "fa-cloud" : "\u{f0c2}",
            "fa-flask" : "\u{f0c3}",
            "fa-scissors" : "\u{f0c4}",
            "fa-files-o" : "\u{f0c5}",
            "fa-paperclip" : "\u{f0c6}",
            "fa-floppy-o" : "\u{f0c7}",
            "fa-square" : "\u{f0c8}",
            "fa-bars" : "\u{f0c9}",
            "fa-list-ul" : "\u{f0ca}",
            "fa-list-ol" : "\u{f0cb}",
            "fa-strikethrough" : "\u{f0cc}",
            "fa-underline" : "\u{f0cd}",
            "fa-table" : "\u{f0ce}",
            "fa-magic" : "\u{f0d0}",
            "fa-truck" : "\u{f0d1}",
            "fa-pinterest" : "\u{f0d2}",
            "fa-pinterest-square" : "\u{f0d3}",
            "fa-google-plus-square" : "\u{f0d4}",
            "fa-google-plus" : "\u{f0d5}",
            "fa-money" : "\u{f0d6}",
            "fa-caret-down" : "\u{f0d7}",
            "fa-caret-up" : "\u{f0d8}",
            "fa-caret-left" : "\u{f0d9}",
            "fa-caret-right" : "\u{f0da}",
            "fa-columns" : "\u{f0db}",
            "fa-sort" : "\u{f0dc}",
            "fa-sort-desc" : "\u{f0dd}",
            "fa-sort-asc" : "\u{f0de}",
            "fa-envelope" : "\u{f0e0}",
            "fa-linkedin" : "\u{f0e1}",
            "fa-undo" : "\u{f0e2}",
            "fa-gavel" : "\u{f0e3}",
            "fa-tachometer" : "\u{f0e4}",
            "fa-comment-o" : "\u{f0e5}",
            "fa-comments-o" : "\u{f0e6}",
            "fa-bolt" : "\u{f0e7}",
            "fa-sitemap" : "\u{f0e8}",
            "fa-umbrella" : "\u{f0e9}",
            "fa-clipboard" : "\u{f0ea}",
            "fa-lightbulb-o" : "\u{f0eb}",
            "fa-exchange" : "\u{f0ec}",
            "fa-cloud-download" : "\u{f0ed}",
            "fa-cloud-upload" : "\u{f0ee}",
            "fa-user-md" : "\u{f0f0}",
            "fa-stethoscope" : "\u{f0f1}",
            "fa-suitcase" : "\u{f0f2}",
            "fa-bell" : "\u{f0f3}",
            "fa-coffee" : "\u{f0f4}",
            "fa-cutlery" : "\u{f0f5}",
            "fa-file-text-o" : "\u{f0f6}",
            "fa-building-o" : "\u{f0f7}",
            "fa-hospital-o" : "\u{f0f8}",
            "fa-ambulance" : "\u{f0f9}",
            "fa-medkit" : "\u{f0fa}",
            "fa-fighter-jet" : "\u{f0fb}",
            "fa-beer" : "\u{f0fc}",
            "fa-h-square" : "\u{f0fd}",
            "fa-plus-square" : "\u{f0fe}",
            "fa-angle-double-left" : "\u{f100}",
            "fa-angle-double-right" : "\u{f101}",
            "fa-angle-double-up" : "\u{f102}",
            "fa-angle-double-down" : "\u{f103}",
            "fa-angle-left" : "\u{f104}",
            "fa-angle-right" : "\u{f105}",
            "fa-angle-up" : "\u{f106}",
            "fa-angle-down" : "\u{f107}",
            "fa-desktop" : "\u{f108}",
            "fa-laptop" : "\u{f109}",
            "fa-tablet" : "\u{f10a}",
            "fa-mobile" : "\u{f10b}",
            "fa-circle-o" : "\u{f10c}",
            "fa-quote-left" : "\u{f10d}",
            "fa-quote-right" : "\u{f10e}",
            "fa-spinner" : "\u{f110}",
            "fa-circle" : "\u{f111}",
            "fa-reply" : "\u{f112}",
            "fa-github-alt" : "\u{f113}",
            "fa-folder-o" : "\u{f114}",
            "fa-folder-open-o" : "\u{f115}",
            "fa-smile-o" : "\u{f118}",
            "fa-frown-o" : "\u{f119}",
            "fa-meh-o" : "\u{f11a}",
            "fa-gamepad" : "\u{f11b}",
            "fa-keyboard-o" : "\u{f11c}",
            "fa-flag-o" : "\u{f11d}",
            "fa-flag-checkered" : "\u{f11e}",
            "fa-terminal" : "\u{f120}",
            "fa-code" : "\u{f121}",
            "fa-reply-all" : "\u{f122}",
            "fa-star-half-o" : "\u{f123}",
            "fa-location-arrow" : "\u{f124}",
            "fa-crop" : "\u{f125}",
            "fa-code-fork" : "\u{f126}",
            "fa-chain-broken" : "\u{f127}",
            "fa-question" : "\u{f128}",
            "fa-info" : "\u{f129}",
            "fa-exclamation" : "\u{f12a}",
            "fa-superscript" : "\u{f12b}",
            "fa-subscript" : "\u{f12c}",
            "fa-eraser" : "\u{f12d}",
            "fa-puzzle-piece" : "\u{f12e}",
            "fa-microphone" : "\u{f130}",
            "fa-microphone-slash" : "\u{f131}",
            "fa-shield" : "\u{f132}",
            "fa-calendar-o" : "\u{f133}",
            "fa-fire-extinguisher" : "\u{f134}",
            "fa-rocket" : "\u{f135}",
            "fa-maxcdn" : "\u{f136}",
            "fa-chevron-circle-left" : "\u{f137}",
            "fa-chevron-circle-right" : "\u{f138}",
            "fa-chevron-circle-up" : "\u{f139}",
            "fa-chevron-circle-down" : "\u{f13a}",
            "fa-html5" : "\u{f13b}",
            "fa-css3" : "\u{f13c}",
            "fa-anchor" : "\u{f13d}",
            "fa-unlock-alt" : "\u{f13e}",
            "fa-bullseye" : "\u{f140}",
            "fa-ellipsis-h" : "\u{f141}",
            "fa-ellipsis-v" : "\u{f142}",
            "fa-rss-square" : "\u{f143}",
            "fa-play-circle" : "\u{f144}",
            "fa-ticket" : "\u{f145}",
            "fa-minus-square" : "\u{f146}",
            "fa-minus-square-o" : "\u{f147}",
            "fa-level-up" : "\u{f148}",
            "fa-level-down" : "\u{f149}",
            "fa-check-square" : "\u{f14a}",
            "fa-pencil-square" : "\u{f14b}",
            "fa-external-link-square" : "\u{f14c}",
            "fa-share-square" : "\u{f14d}",
            "fa-compass" : "\u{f14e}",
            "fa-caret-square-o-down" : "\u{f150}",
            "fa-caret-square-o-up" : "\u{f151}",
            "fa-caret-square-o-right" : "\u{f152}",
            "fa-eur" : "\u{f153}",
            "fa-gbp" : "\u{f154}",
            "fa-usd" : "\u{f155}",
            "fa-inr" : "\u{f156}",
            "fa-jpy" : "\u{f157}",
            "fa-rub" : "\u{f158}",
            "fa-krw" : "\u{f159}",
            "fa-btc" : "\u{f15a}",
            "fa-file" : "\u{f15b}",
            "fa-file-text" : "\u{f15c}",
            "fa-sort-alpha-asc" : "\u{f15d}",
            "fa-sort-alpha-desc" : "\u{f15e}",
            "fa-sort-amount-asc" : "\u{f160}",
            "fa-sort-amount-desc" : "\u{f161}",
            "fa-sort-numeric-asc" : "\u{f162}",
            "fa-sort-numeric-desc" : "\u{f163}",
            "fa-thumbs-up" : "\u{f164}",
            "fa-thumbs-down" : "\u{f165}",
            "fa-youtube-square" : "\u{f166}",
            "fa-youtube" : "\u{f167}",
            "fa-xing" : "\u{f168}",
            "fa-xing-square" : "\u{f169}",
            "fa-youtube-play" : "\u{f16a}",
            "fa-dropbox" : "\u{f16b}",
            "fa-stack-overflow" : "\u{f16c}",
            "fa-instagram" : "\u{f16d}",
            "fa-flickr" : "\u{f16e}",
            "fa-adn" : "\u{f170}",
            "fa-bitbucket" : "\u{f171}",
            "fa-bitbucket-square" : "\u{f172}",
            "fa-tumblr" : "\u{f173}",
            "fa-tumblr-square" : "\u{f174}",
            "fa-long-arrow-down" : "\u{f175}",
            "fa-long-arrow-up" : "\u{f176}",
            "fa-long-arrow-left" : "\u{f177}",
            "fa-long-arrow-right" : "\u{f178}",
            "fa-apple" : "\u{f179}",
            "fa-windows" : "\u{f17a}",
            "fa-android" : "\u{f17b}",
            "fa-linux" : "\u{f17c}",
            "fa-dribbble" : "\u{f17d}",
            "fa-skype" : "\u{f17e}",
            "fa-foursquare" : "\u{f180}",
            "fa-trello" : "\u{f181}",
            "fa-female" : "\u{f182}",
            "fa-male" : "\u{f183}",
            "fa-gratipay" : "\u{f184}",
            "fa-sun-o" : "\u{f185}",
            "fa-moon-o" : "\u{f186}",
            "fa-archive" : "\u{f187}",
            "fa-bug" : "\u{f188}",
            "fa-vk" : "\u{f189}",
            "fa-weibo" : "\u{f18a}",
            "fa-renren" : "\u{f18b}",
            "fa-pagelines" : "\u{f18c}",
            "fa-stack-exchange" : "\u{f18d}",
            "fa-arrow-circle-o-right" : "\u{f18e}",
            "fa-arrow-circle-o-left" : "\u{f190}",
            "fa-caret-square-o-left" : "\u{f191}",
            "fa-dot-circle-o" : "\u{f192}",
            "fa-wheelchair" : "\u{f193}",
            "fa-vimeo-square" : "\u{f194}",
            "fa-try" : "\u{f195}",
            "fa-plus-square-o" : "\u{f196}",
            "fa-space-shuttle" : "\u{f197}",
            "fa-slack" : "\u{f198}",
            "fa-envelope-square" : "\u{f199}",
            "fa-wordpress" : "\u{f19a}",
            "fa-openid" : "\u{f19b}",
            "fa-university" : "\u{f19c}",
            "fa-graduation-cap" : "\u{f19d}",
            "fa-yahoo" : "\u{f19e}",
            "fa-google" : "\u{f1a0}",
            "fa-reddit" : "\u{f1a1}",
            "fa-reddit-square" : "\u{f1a2}",
            "fa-stumbleupon-circle" : "\u{f1a3}",
            "fa-stumbleupon" : "\u{f1a4}",
            "fa-delicious" : "\u{f1a5}",
            "fa-digg" : "\u{f1a6}",
            "fa-pied-piper" : "\u{f1a7}",
            "fa-pied-piper-alt" : "\u{f1a8}",
            "fa-drupal" : "\u{f1a9}",
            "fa-joomla" : "\u{f1aa}",
            "fa-language" : "\u{f1ab}",
            "fa-fax" : "\u{f1ac}",
            "fa-building" : "\u{f1ad}",
            "fa-child" : "\u{f1ae}",
            "fa-paw" : "\u{f1b0}",
            "fa-spoon" : "\u{f1b1}",
            "fa-cube" : "\u{f1b2}",
            "fa-cubes" : "\u{f1b3}",
            "fa-behance" : "\u{f1b4}",
            "fa-behance-square" : "\u{f1b5}",
            "fa-steam" : "\u{f1b6}",
            "fa-steam-square" : "\u{f1b7}",
            "fa-recycle" : "\u{f1b8}",
            "fa-automobile" : "\u{f1b9}",
            "fa-car" : "\u{f1b9}",
            "fa-taxi" : "\u{f1ba}",
            "fa-tree" : "\u{f1bb}",
            "fa-spotify" : "\u{f1bc}",
            "fa-deviantart" : "\u{f1bd}",
            "fa-soundcloud" : "\u{f1be}",
            "fa-database" : "\u{f1c0}",
            "fa-file-pdf-o" : "\u{f1c1}",
            "fa-file-word-o" : "\u{f1c2}",
            "fa-file-excel-o" : "\u{f1c3}",
            "fa-file-powerpoint-o" : "\u{f1c4}",
            "fa-file-image-o" : "\u{f1c5}",
            "fa-file-archive-o" : "\u{f1c6}",
            "fa-file-audio-o" : "\u{f1c7}",
            "fa-file-video-o" : "\u{f1c8}",
            "fa-file-code-o" : "\u{f1c9}",
            "fa-vine" : "\u{f1ca}",
            "fa-codepen" : "\u{f1cb}",
            "fa-jsfiddle" : "\u{f1cc}",
            "fa-life-ring" : "\u{f1cd}",
            "fa-circle-o-notch" : "\u{f1ce}",
            "fa-rebel" : "\u{f1d0}",
            "fa-empire" : "\u{f1d1}",
            "fa-git-square" : "\u{f1d2}",
            "fa-git" : "\u{f1d3}",
            "fa-hacker-news" : "\u{f1d4}",
            "fa-tencent-weibo" : "\u{f1d5}",
            "fa-qq" : "\u{f1d6}",
            "fa-weixin" : "\u{f1d7}",
            "fa-paper-plane" : "\u{f1d8}",
            "fa-paper-plane-o" : "\u{f1d9}",
            "fa-history" : "\u{f1da}",
            "fa-circle-thin" : "\u{f1db}",
            "fa-header" : "\u{f1dc}",
            "fa-paragraph" : "\u{f1dd}",
            "fa-sliders" : "\u{f1de}",
            "fa-share-alt" : "\u{f1e0}",
            "fa-share-alt-square" : "\u{f1e1}",
            "fa-bomb" : "\u{f1e2}",
            "fa-futbol-o" : "\u{f1e3}",
            "fa-tty" : "\u{f1e4}",
            "fa-binoculars" : "\u{f1e5}",
            "fa-plug" : "\u{f1e6}",
            "fa-slideshare" : "\u{f1e7}",
            "fa-twitch" : "\u{f1e8}",
            "fa-yelp" : "\u{f1e9}",
            "fa-newspaper-o" : "\u{f1ea}",
            "fa-wifi" : "\u{f1eb}",
            "fa-calculator" : "\u{f1ec}",
            "fa-paypal" : "\u{f1ed}",
            "fa-google-wallet" : "\u{f1ee}",
            "fa-cc-visa" : "\u{f1f0}",
            "fa-cc-mastercard" : "\u{f1f1}",
            "fa-cc-discover" : "\u{f1f2}",
            "fa-cc-amex" : "\u{f1f3}",
            "fa-cc-paypal" : "\u{f1f4}",
            "fa-cc-stripe" : "\u{f1f5}",
            "fa-bell-slash" : "\u{f1f6}",
            "fa-bell-slash-o" : "\u{f1f7}",
            "fa-trash" : "\u{f1f8}",
            "fa-copyright" : "\u{f1f9}",
            "fa-at" : "\u{f1fa}",
            "fa-eyedropper" : "\u{f1fb}",
            "fa-paint-brush" : "\u{f1fc}",
            "fa-birthday-cake" : "\u{f1fd}",
            "fa-area-chart" : "\u{f1fe}",
            "fa-pie-chart" : "\u{f200}",
            "fa-line-chart" : "\u{f201}",
            "fa-lastfm" : "\u{f202}",
            "fa-lastfm-square" : "\u{f203}",
            "fa-toggle-off" : "\u{f204}",
            "fa-toggle-on" : "\u{f205}",
            "fa-bicycle" : "\u{f206}",
            "fa-bus" : "\u{f207}",
            "fa-ioxhost" : "\u{f208}",
            "fa-angellist" : "\u{f209}",
            "fa-cc" : "\u{f20a}",
            "fa-ils" : "\u{f20b}",
            "fa-meanpath" : "\u{f20c}",
            "fa-buysellads" : "\u{f20d}",
            "fa-connectdevelop" : "\u{f20e}",
            "fa-dashcube" : "\u{f210}",
            "fa-forumbee" : "\u{f211}",
            "fa-leanpub" : "\u{f212}",
            "fa-sellsy" : "\u{f213}",
            "fa-shirtsinbulk" : "\u{f214}",
            "fa-simplybuilt" : "\u{f215}",
            "fa-skyatlas" : "\u{f216}",
            "fa-cart-plus" : "\u{f217}",
            "fa-cart-arrow-down" : "\u{f218}",
            "fa-diamond" : "\u{f219}",
            "fa-ship" : "\u{f21a}",
            "fa-user-secret" : "\u{f21b}",
            "fa-motorcycle" : "\u{f21c}",
            "fa-street-view" : "\u{f21d}",
            "fa-heartbeat" : "\u{f21e}",
            "fa-venus" : "\u{f221}",
            "fa-mars" : "\u{f222}",
            "fa-mercury" : "\u{f223}",
            "fa-transgender" : "\u{f224}",
            "fa-transgender-alt" : "\u{f225}",
            "fa-venus-double" : "\u{f226}",
            "fa-mars-double" : "\u{f227}",
            "fa-venus-mars" : "\u{f228}",
            "fa-mars-stroke" : "\u{f229}",
            "fa-mars-stroke-v" : "\u{f22a}",
            "fa-mars-stroke-h" : "\u{f22b}",
            "fa-neuter" : "\u{f22c}",
            "fa-genderless" : "\u{f22d}",
            "fa-facebook-official" : "\u{f230}",
            "fa-pinterest-p" : "\u{f231}",
            "fa-whatsapp" : "\u{f232}",
            "fa-server" : "\u{f233}",
            "fa-user-plus" : "\u{f234}",
            "fa-user-times" : "\u{f235}",
            "fa-bed" : "\u{f236}",
            "fa-viacoin" : "\u{f237}",
            "fa-train" : "\u{f238}",
            "fa-subway" : "\u{f239}",
            "fa-medium" : "\u{f23a}",
            "fa-y-combinator" : "\u{f23b}",
            "fa-optin-monster" : "\u{f23c}",
            "fa-opencart" : "\u{f23d}",
            "fa-expeditedssl" : "\u{f23e}",
            "fa-battery-full" : "\u{f240}",
            "fa-battery-three-quarters" : "\u{f241}",
            "fa-battery-half" : "\u{f242}",
            "fa-battery-quarter" : "\u{f243}",
            "fa-battery-empty" : "\u{f244}",
            "fa-mouse-pointer" : "\u{f245}",
            "fa-i-cursor" : "\u{f246}",
            "fa-object-group" : "\u{f247}",
            "fa-object-ungroup" : "\u{f248}",
            "fa-sticky-note" : "\u{f249}",
            "fa-sticky-note-o" : "\u{f24a}",
            "fa-cc-jcb" : "\u{f24b}",
            "fa-cc-diners-club" : "\u{f24c}",
            "fa-clone" : "\u{f24d}",
            "fa-balance-scale" : "\u{f24e}",
            "fa-hourglass-o" : "\u{f250}",
            "fa-hourglass-start" : "\u{f251}",
            "fa-hourglass-half" : "\u{f252}",
            "fa-hourglass-end" : "\u{f253}",
            "fa-hourglass" : "\u{f254}",
            "fa-hand-rock-o" : "\u{f255}",
            "fa-hand-paper-o" : "\u{f256}",
            "fa-hand-scissors-o" : "\u{f257}",
            "fa-hand-lizard-o" : "\u{f258}",
            "fa-hand-spock-o" : "\u{f259}",
            "fa-hand-pointer-o" : "\u{f25a}",
            "fa-hand-peace-o" : "\u{f25b}",
            "fa-trademark" : "\u{f25c}",
            "fa-registered" : "\u{f25d}",
            "fa-creative-commons" : "\u{f25e}",
            "fa-gg" : "\u{f260}",
            "fa-gg-circle" : "\u{f261}",
            "fa-tripadvisor" : "\u{f262}",
            "fa-odnoklassniki" : "\u{f263}",
            "fa-odnoklassniki-square" : "\u{f264}",
            "fa-get-pocket" : "\u{f265}",
            "fa-wikipedia-w" : "\u{f266}",
            "fa-safari" : "\u{f267}",
            "fa-chrome" : "\u{f268}",
            "fa-firefox" : "\u{f269}",
            "fa-opera" : "\u{f26a}",
            "fa-internet-explorer" : "\u{f26b}",
            "fa-television" : "\u{f26c}",
            "fa-contao" : "\u{f26d}",
            "fa-500px" : "\u{f26e}",
            "fa-amazon" : "\u{f270}",
            "fa-calendar-plus-o" : "\u{f271}",
            "fa-calendar-minus-o" : "\u{f272}",
            "fa-calendar-times-o" : "\u{f273}",
            "fa-calendar-check-o" : "\u{f274}",
            "fa-industry" : "\u{f275}",
            "fa-map-pin" : "\u{f276}",
            "fa-map-signs" : "\u{f277}",
            "fa-map-o" : "\u{f278}",
            "fa-map" : "\u{f279}",
            "fa-commenting" : "\u{f27a}",
            "fa-commenting-o" : "\u{f27b}",
            "fa-houzz" : "\u{f27c}",
            "fa-vimeo" : "\u{f27d}",
            "fa-black-tie" : "\u{f27e}",
            "fa-fonticons" : "\u{f280}" 
        ]
        
        if let raw = dict[code], icon = FontAwesome(rawValue: raw)  {
            return self.fontAwesomeIconWithName(icon)
        }
        
        return nil
    }
}


