// Icon.swift
//
// Copyright (c) 2014-2015 Thi Doan
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.

/// An enumaration of FontAwesome icon names.
public enum Icon: String {
    case faGlass = "fa-glass"
    case faMusic = "fa-music"
    case faSearch = "fa-search"
    case faEnvelopeOutlined = "fa-envelope-o"
    case faHeart = "fa-heart"
    case faStar = "fa-star"
    case faStarOutlined = "fa-star-o"
    case faUser = "fa-user"
    case faFilm = "fa-film"
    case faThLarge = "fa-th-large"
    case faTh = "fa-th"
    case faThList = "fa-th-list"
    case faCheck = "fa-check"
    case faTimes = "fa-times"
    case faSearchPlus = "fa-search-plus"
    case faSearchMinus = "fa-search-minus"
    case faPowerOff = "fa-power-off"
    case faSignal = "fa-signal"
    case faCog = "fa-cog"
    case faTrashOutlined = "fa-trash-o"
    case faHome = "fa-home"
    case faFileOutlined = "fa-file-o"
    case faClockOutlined = "fa-clock-o"
    case faRoad = "fa-road"
    case faDownload = "fa-download"
    case faArrowCircleOutlinedDown = "fa-arrow-circle-o-down"
    case faArrowCircleOutlinedUp = "fa-arrow-circle-o-up"
    case faInbox = "fa-inbox"
    case faPlayCircleOutlined = "fa-play-circle-o"
    case faRepeat = "fa-repeat"
    case faRefresh = "fa-refresh"
    case faListAlt = "fa-list-alt"
    case faLock = "fa-lock"
    case faFlag = "fa-flag"
    case faHeadphones = "fa-headphones"
    case faVolumeOff = "fa-volume-off"
    case faVolumeDown = "fa-volume-down"
    case faVolumeUp = "fa-volume-up"
    case faQrcode = "fa-qrcode"
    case faBarcode = "fa-barcode"
    case faTag = "fa-tag"
    case faTags = "fa-tags"
    case faBook = "fa-book"
    case faBookmark = "fa-bookmark"
    case faPrint = "fa-print"
    case faCamera = "fa-camera"
    case faFont = "fa-font"
    case faBold = "fa-bold"
    case faItalic = "fa-italic"
    case faTextHeight = "fa-text-height"
    case faTextWidth = "fa-text-width"
    case faAlignLeft = "fa-align-left"
    case faAlignCenter = "fa-align-center"
    case faAlignRight = "fa-align-right"
    case faAlignJustify = "fa-align-justify"
    case faList = "fa-list"
    case faOutdent = "fa-outdent"
    case faIndent = "fa-indent"
    case faVideoCamera = "fa-video-camera"
    case faPictureOutlined = "fa-picture-o"
    case faPencil = "fa-pencil"
    case faMapMarker = "fa-map-marker"
    case faAdjust = "fa-adjust"
    case faTint = "fa-tint"
    case faPencilSquareOutlined = "fa-pencil-square-o"
    case faShareSquareOutlined = "fa-share-square-o"
    case faCheckSquareOutlined = "fa-check-square-o"
    case faArrows = "fa-arrows"
    case faStepBackward = "fa-step-backward"
    case faFastBackward = "fa-fast-backward"
    case faBackward = "fa-backward"
    case faPlay = "fa-play"
    case faPause = "fa-pause"
    case faStop = "fa-stop"
    case faForward = "fa-forward"
    case faFastForward = "fa-fast-forward"
    case faStepForward = "fa-step-forward"
    case faEject = "fa-eject"
    case faChevronLeft = "fa-chevron-left"
    case faChevronRight = "fa-chevron-right"
    case faPlusCircle = "fa-plus-circle"
    case faMinusCircle = "fa-minus-circle"
    case faTimesCircle = "fa-times-circle"
    case faCheckCircle = "fa-check-circle"
    case faQuestionCircle = "fa-question-circle"
    case faInfoCircle = "fa-info-circle"
    case faCrosshairs = "fa-crosshairs"
    case faTimesCircleOutlined = "fa-times-circle-o"
    case faCheckCircleOutlined = "fa-check-circle-o"
    case faBan = "fa-ban"
    case faArrowLeft = "fa-arrow-left"
    case faArrowRight = "fa-arrow-right"
    case faArrowUp = "fa-arrow-up"
    case faArrowDown = "fa-arrow-down"
    case faShare = "fa-share"
    case faExpand = "fa-expand"
    case faCompress = "fa-compress"
    case faPlus = "fa-plus"
    case faMinus = "fa-minus"
    case faAsterisk = "fa-asterisk"
    case faExclamationCircle = "fa-exclamation-circle"
    case faGift = "fa-gift"
    case faLeaf = "fa-leaf"
    case faFire = "fa-fire"
    case faEye = "fa-eye"
    case faEyeSlash = "fa-eye-slash"
    case faExclamationTriangle = "fa-exclamation-triangle"
    case faPlane = "fa-plane"
    case faCalendar = "fa-calendar"
    case faRandom = "fa-random"
    case faComment = "fa-comment"
    case faMagnet = "fa-magnet"
    case faChevronUp = "fa-chevron-up"
    case faChevronDown = "fa-chevron-down"
    case faRetweet = "fa-retweet"
    case faShoppingCart = "fa-shopping-cart"
    case faFolder = "fa-folder"
    case faFolderOpen = "fa-folder-open"
    case faArrowsV = "fa-arrows-v"
    case faArrowsH = "fa-arrows-h"
    case faBarChart = "fa-bar-chart"
    case faTwitterSquare = "fa-twitter-square"
    case faFacebookSquare = "fa-facebook-square"
    case faCameraRetro = "fa-camera-retro"
    case faKey = "fa-key"
    case faCogs = "fa-cogs"
    case faComments = "fa-comments"
    case faThumbsOutlinedUp = "fa-thumbs-o-up"
    case faThumbsOutlinedDown = "fa-thumbs-o-down"
    case faStarHalf = "fa-star-half"
    case faHeartOutlined = "fa-heart-o"
    case faSignOut = "fa-sign-out"
    case faLinkedinSquare = "fa-linkedin-square"
    case faThumbTack = "fa-thumb-tack"
    case faExternalLink = "fa-external-link"
    case faSignIn = "fa-sign-in"
    case faTrophy = "fa-trophy"
    case faGithubSquare = "fa-github-square"
    case faUpload = "fa-upload"
    case faLemonOutlined = "fa-lemon-o"
    case faPhone = "fa-phone"
    case faSquareOutlined = "fa-square-o"
    case faBookmarkOutlined = "fa-bookmark-o"
    case faPhoneSquare = "fa-phone-square"
    case faTwitter = "fa-twitter"
    case faFacebook = "fa-facebook"
    case faGithub = "fa-github"
    case faUnlock = "fa-unlock"
    case faCreditCard = "fa-credit-card"
    case faRss = "fa-rss"
    case faHddOutlined = "fa-hdd-o"
    case faBullhorn = "fa-bullhorn"
    case faBell = "fa-bell"
    case faCertificate = "fa-certificate"
    case faHandOutlinedRight = "fa-hand-o-right"
    case faHandOutlinedLeft = "fa-hand-o-left"
    case faHandOutlinedUp = "fa-hand-o-up"
    case faHandOutlinedDown = "fa-hand-o-down"
    case faArrowCircleLeft = "fa-arrow-circle-left"
    case faArrowCircleRight = "fa-arrow-circle-right"
    case faArrowCircleUp = "fa-arrow-circle-up"
    case faArrowCircleDown = "fa-arrow-circle-down"
    case faGlobe = "fa-globe"
    case faWrench = "fa-wrench"
    case faTasks = "fa-tasks"
    case faFilter = "fa-filter"
    case faBriefcase = "fa-briefcase"
    case faArrowsAlt = "fa-arrows-alt"
    case faUsers = "fa-users"
    case faLink = "fa-link"
    case faCloud = "fa-cloud"
    case faFlask = "fa-flask"
    case faScissors = "fa-scissors"
    case faFilesOutlined = "fa-files-o"
    case faPaperclip = "fa-paperclip"
    case faFloppyOutlined = "fa-floppy-o"
    case faSquare = "fa-square"
    case faBars = "fa-bars"
    case faListUl = "fa-list-ul"
    case faListOl = "fa-list-ol"
    case faStrikethrough = "fa-strikethrough"
    case faUnderline = "fa-underline"
    case faTable = "fa-table"
    case faMagic = "fa-magic"
    case faTruck = "fa-truck"
    case faPinterest = "fa-pinterest"
    case faPinterestSquare = "fa-pinterest-square"
    case faGooglePlusSquare = "fa-google-plus-square"
    case faGooglePlus = "fa-google-plus"
    case faMoney = "fa-money"
    case faCaretDown = "fa-caret-down"
    case faCaretUp = "fa-caret-up"
    case faCaretLeft = "fa-caret-left"
    case faCaretRight = "fa-caret-right"
    case faColumns = "fa-columns"
    case faSort = "fa-sort"
    case faSortDesc = "fa-sort-desc"
    case faSortAsc = "fa-sort-asc"
    case faEnvelope = "fa-envelope"
    case faLinkedin = "fa-linkedin"
    case faUndo = "fa-undo"
    case faGavel = "fa-gavel"
    case faTachometer = "fa-tachometer"
    case faCommentOutlined = "fa-comment-o"
    case faCommentsOutlined = "fa-comments-o"
    case faBolt = "fa-bolt"
    case faSitemap = "fa-sitemap"
    case faUmbrella = "fa-umbrella"
    case faClipboard = "fa-clipboard"
    case faLightbulbOutlined = "fa-lightbulb-o"
    case faExchange = "fa-exchange"
    case faCloudDownload = "fa-cloud-download"
    case faCloudUpload = "fa-cloud-upload"
    case faUserMd = "fa-user-md"
    case faStethoscope = "fa-stethoscope"
    case faSuitcase = "fa-suitcase"
    case faBellOutlined = "fa-bell-o"
    case faCoffee = "fa-coffee"
    case faCutlery = "fa-cutlery"
    case faFileTextOutlined = "fa-file-text-o"
    case faBuildingOutlined = "fa-building-o"
    case faHospitalOutlined = "fa-hospital-o"
    case faAmbulance = "fa-ambulance"
    case faMedkit = "fa-medkit"
    case faFighterJet = "fa-fighter-jet"
    case faBeer = "fa-beer"
    case faHSquare = "fa-h-square"
    case faPlusSquare = "fa-plus-square"
    case faAngleDoubleLeft = "fa-angle-double-left"
    case faAngleDoubleRight = "fa-angle-double-right"
    case faAngleDoubleUp = "fa-angle-double-up"
    case faAngleDoubleDown = "fa-angle-double-down"
    case faAngleLeft = "fa-angle-left"
    case faAngleRight = "fa-angle-right"
    case faAngleUp = "fa-angle-up"
    case faAngleDown = "fa-angle-down"
    case faDesktop = "fa-desktop"
    case faLaptop = "fa-laptop"
    case faTablet = "fa-tablet"
    case faMobile = "fa-mobile"
    case faCircleOutlined = "fa-circle-o"
    case faQuoteLeft = "fa-quote-left"
    case faQuoteRight = "fa-quote-right"
    case faSpinner = "fa-spinner"
    case faCircle = "fa-circle"
    case faReply = "fa-reply"
    case faGithubAlt = "fa-github-alt"
    case faFolderOutlined = "fa-folder-o"
    case faFolderOpenOutlined = "fa-folder-open-o"
    case faSmileOutlined = "fa-smile-o"
    case faFrownOutlined = "fa-frown-o"
    case faMehOutlined = "fa-meh-o"
    case faGamepad = "fa-gamepad"
    case faKeyboardOutlined = "fa-keyboard-o"
    case faFlagOutlined = "fa-flag-o"
    case faFlagCheckered = "fa-flag-checkered"
    case faTerminal = "fa-terminal"
    case faCode = "fa-code"
    case faReplyAll = "fa-reply-all"
    case faStarHalfOutlined = "fa-star-half-o"
    case faLocationArrow = "fa-location-arrow"
    case faCrop = "fa-crop"
    case faCodeFork = "fa-code-fork"
    case faChainBroken = "fa-chain-broken"
    case faQuestion = "fa-question"
    case faInfo = "fa-info"
    case faExclamation = "fa-exclamation"
    case faSuperscript = "fa-superscript"
    case faSubscript = "fa-subscript"
    case faEraser = "fa-eraser"
    case faPuzzlePiece = "fa-puzzle-piece"
    case faMicrophone = "fa-microphone"
    case faMicrophoneSlash = "fa-microphone-slash"
    case faShield = "fa-shield"
    case faCalendarOutlined = "fa-calendar-o"
    case faFireExtinguisher = "fa-fire-extinguisher"
    case faRocket = "fa-rocket"
    case faMaxcdn = "fa-maxcdn"
    case faChevronCircleLeft = "fa-chevron-circle-left"
    case faChevronCircleRight = "fa-chevron-circle-right"
    case faChevronCircleUp = "fa-chevron-circle-up"
    case faChevronCircleDown = "fa-chevron-circle-down"
    case faHtml5 = "fa-html5"
    case faCss3 = "fa-css3"
    case faAnchor = "fa-anchor"
    case faUnlockAlt = "fa-unlock-alt"
    case faBullseye = "fa-bullseye"
    case faEllipsisH = "fa-ellipsis-h"
    case faEllipsisV = "fa-ellipsis-v"
    case faRssSquare = "fa-rss-square"
    case faPlayCircle = "fa-play-circle"
    case faTicket = "fa-ticket"
    case faMinusSquare = "fa-minus-square"
    case faMinusSquareOutlined = "fa-minus-square-o"
    case faLevelUp = "fa-level-up"
    case faLevelDown = "fa-level-down"
    case faCheckSquare = "fa-check-square"
    case faPencilSquare = "fa-pencil-square"
    case faExternalLinkSquare = "fa-external-link-square"
    case faShareSquare = "fa-share-square"
    case faCompass = "fa-compass"
    case faCaretSquareOutlinedDown = "fa-caret-square-o-down"
    case faCaretSquareOutlinedUp = "fa-caret-square-o-up"
    case faCaretSquareOutlinedRight = "fa-caret-square-o-right"
    case faEur = "fa-eur"
    case faGbp = "fa-gbp"
    case faUsd = "fa-usd"
    case faInr = "fa-inr"
    case faJpy = "fa-jpy"
    case faRub = "fa-rub"
    case faKrw = "fa-krw"
    case faBtc = "fa-btc"
    case faFile = "fa-file"
    case faFileText = "fa-file-text"
    case faSortAlphaAsc = "fa-sort-alpha-asc"
    case faSortAlphaDesc = "fa-sort-alpha-desc"
    case faSortAmountAsc = "fa-sort-amount-asc"
    case faSortAmountDesc = "fa-sort-amount-desc"
    case faSortNumericAsc = "fa-sort-numeric-asc"
    case faSortNumericDesc = "fa-sort-numeric-desc"
    case faThumbsUp = "fa-thumbs-up"
    case faThumbsDown = "fa-thumbs-down"
    case faYoutubeSquare = "fa-youtube-square"
    case faYoutube = "fa-youtube"
    case faXing = "fa-xing"
    case faXingSquare = "fa-xing-square"
    case faYoutubePlay = "fa-youtube-play"
    case faDropbox = "fa-dropbox"
    case faStackOverflow = "fa-stack-overflow"
    case faInstagram = "fa-instagram"
    case faFlickr = "fa-flickr"
    case faAdn = "fa-adn"
    case faBitbucket = "fa-bitbucket"
    case faBitbucketSquare = "fa-bitbucket-square"
    case faTumblr = "fa-tumblr"
    case faTumblrSquare = "fa-tumblr-square"
    case faLongArrowDown = "fa-long-arrow-down"
    case faLongArrowUp = "fa-long-arrow-up"
    case faLongArrowLeft = "fa-long-arrow-left"
    case faLongArrowRight = "fa-long-arrow-right"
    case faApple = "fa-apple"
    case faWindows = "fa-windows"
    case faAndroid = "fa-android"
    case faLinux = "fa-linux"
    case faDribbble = "fa-dribbble"
    case faSkype = "fa-skype"
    case faFoursquare = "fa-foursquare"
    case faTrello = "fa-trello"
    case faFemale = "fa-female"
    case faMale = "fa-male"
    case faGratipay = "fa-gratipay"
    case faSunOutlined = "fa-sun-o"
    case faMoonOutlined = "fa-moon-o"
    case faArchive = "fa-archive"
    case faBug = "fa-bug"
    case faVk = "fa-vk"
    case faWeibo = "fa-weibo"
    case faRenren = "fa-renren"
    case faPagelines = "fa-pagelines"
    case faStackExchange = "fa-stack-exchange"
    case faArrowCircleOutlinedRight = "fa-arrow-circle-o-right"
    case faArrowCircleOutlinedLeft = "fa-arrow-circle-o-left"
    case faCaretSquareOutlinedLeft = "fa-caret-square-o-left"
    case faDotCircleOutlined = "fa-dot-circle-o"
    case faWheelchair = "fa-wheelchair"
    case faVimeoSquare = "fa-vimeo-square"
    case faTry = "fa-try"
    case faPlusSquareOutlined = "fa-plus-square-o"
    case faSpaceShuttle = "fa-space-shuttle"
    case faSlack = "fa-slack"
    case faEnvelopeSquare = "fa-envelope-square"
    case faWordpress = "fa-wordpress"
    case faOpenid = "fa-openid"
    case faUniversity = "fa-university"
    case faGraduationCap = "fa-graduation-cap"
    case faYahoo = "fa-yahoo"
    case faGoogle = "fa-google"
    case faReddit = "fa-reddit"
    case faRedditSquare = "fa-reddit-square"
    case faStumbleuponCircle = "fa-stumbleupon-circle"
    case faStumbleupon = "fa-stumbleupon"
    case faDelicious = "fa-delicious"
    case faDigg = "fa-digg"
    case faPiedPiperPp = "fa-pied-piper-pp"
    case faPiedPiperAlt = "fa-pied-piper-alt"
    case faDrupal = "fa-drupal"
    case faJoomla = "fa-joomla"
    case faLanguage = "fa-language"
    case faFax = "fa-fax"
    case faBuilding = "fa-building"
    case faChild = "fa-child"
    case faPaw = "fa-paw"
    case faSpoon = "fa-spoon"
    case faCube = "fa-cube"
    case faCubes = "fa-cubes"
    case faBehance = "fa-behance"
    case faBehanceSquare = "fa-behance-square"
    case faSteam = "fa-steam"
    case faSteamSquare = "fa-steam-square"
    case faRecycle = "fa-recycle"
    case faCar = "fa-car"
    case faTaxi = "fa-taxi"
    case faTree = "fa-tree"
    case faSpotify = "fa-spotify"
    case faDeviantart = "fa-deviantart"
    case faSoundcloud = "fa-soundcloud"
    case faDatabase = "fa-database"
    case faFilePdfOutlined = "fa-file-pdf-o"
    case faFileWordOutlined = "fa-file-word-o"
    case faFileExcelOutlined = "fa-file-excel-o"
    case faFilePowerpointOutlined = "fa-file-powerpoint-o"
    case faFileImageOutlined = "fa-file-image-o"
    case faFileArchiveOutlined = "fa-file-archive-o"
    case faFileAudioOutlined = "fa-file-audio-o"
    case faFileVideoOutlined = "fa-file-video-o"
    case faFileCodeOutlined = "fa-file-code-o"
    case faVine = "fa-vine"
    case faCodepen = "fa-codepen"
    case faJsfiddle = "fa-jsfiddle"
    case faLifeRing = "fa-life-ring"
    case faCircleOutlinedNotch = "fa-circle-o-notch"
    case faRebel = "fa-rebel"
    case faEmpire = "fa-empire"
    case faGitSquare = "fa-git-square"
    case faGit = "fa-git"
    case faHackerNews = "fa-hacker-news"
    case faTencentWeibo = "fa-tencent-weibo"
    case faQq = "fa-qq"
    case faWeixin = "fa-weixin"
    case faPaperPlane = "fa-paper-plane"
    case faPaperPlaneOutlined = "fa-paper-plane-o"
    case faHistory = "fa-history"
    case faCircleThin = "fa-circle-thin"
    case faHeader = "fa-header"
    case faParagraph = "fa-paragraph"
    case faSliders = "fa-sliders"
    case faShareAlt = "fa-share-alt"
    case faShareAltSquare = "fa-share-alt-square"
    case faBomb = "fa-bomb"
    case faFutbolOutlined = "fa-futbol-o"
    case faTty = "fa-tty"
    case faBinoculars = "fa-binoculars"
    case faPlug = "fa-plug"
    case faSlideshare = "fa-slideshare"
    case faTwitch = "fa-twitch"
    case faYelp = "fa-yelp"
    case faNewspaperOutlined = "fa-newspaper-o"
    case faWifi = "fa-wifi"
    case faCalculator = "fa-calculator"
    case faPaypal = "fa-paypal"
    case faGoogleWallet = "fa-google-wallet"
    case faCcVisa = "fa-cc-visa"
    case faCcMastercard = "fa-cc-mastercard"
    case faCcDiscover = "fa-cc-discover"
    case faCcAmex = "fa-cc-amex"
    case faCcPaypal = "fa-cc-paypal"
    case faCcStripe = "fa-cc-stripe"
    case faBellSlash = "fa-bell-slash"
    case faBellSlashOutlined = "fa-bell-slash-o"
    case faTrash = "fa-trash"
    case faCopyright = "fa-copyright"
    case faAt = "fa-at"
    case faEyedropper = "fa-eyedropper"
    case faPaintBrush = "fa-paint-brush"
    case faBirthdayCake = "fa-birthday-cake"
    case faAreaChart = "fa-area-chart"
    case faPieChart = "fa-pie-chart"
    case faLineChart = "fa-line-chart"
    case faLastfm = "fa-lastfm"
    case faLastfmSquare = "fa-lastfm-square"
    case faToggleOff = "fa-toggle-off"
    case faToggleOn = "fa-toggle-on"
    case faBicycle = "fa-bicycle"
    case faBus = "fa-bus"
    case faIoxhost = "fa-ioxhost"
    case faAngellist = "fa-angellist"
    case faCc = "fa-cc"
    case faIls = "fa-ils"
    case faMeanpath = "fa-meanpath"
    case faBuysellads = "fa-buysellads"
    case faConnectdevelop = "fa-connectdevelop"
    case faDashcube = "fa-dashcube"
    case faForumbee = "fa-forumbee"
    case faLeanpub = "fa-leanpub"
    case faSellsy = "fa-sellsy"
    case faShirtsinbulk = "fa-shirtsinbulk"
    case faSimplybuilt = "fa-simplybuilt"
    case faSkyatlas = "fa-skyatlas"
    case faCartPlus = "fa-cart-plus"
    case faCartArrowDown = "fa-cart-arrow-down"
    case faDiamond = "fa-diamond"
    case faShip = "fa-ship"
    case faUserSecret = "fa-user-secret"
    case faMotorcycle = "fa-motorcycle"
    case faStreetView = "fa-street-view"
    case faHeartbeat = "fa-heartbeat"
    case faVenus = "fa-venus"
    case faMars = "fa-mars"
    case faMercury = "fa-mercury"
    case faTransgender = "fa-transgender"
    case faTransgenderAlt = "fa-transgender-alt"
    case faVenusDouble = "fa-venus-double"
    case faMarsDouble = "fa-mars-double"
    case faVenusMars = "fa-venus-mars"
    case faMarsStroke = "fa-mars-stroke"
    case faMarsStrokeV = "fa-mars-stroke-v"
    case faMarsStrokeH = "fa-mars-stroke-h"
    case faNeuter = "fa-neuter"
    case faGenderless = "fa-genderless"
    case faFacebookOfficial = "fa-facebook-official"
    case faPinterestP = "fa-pinterest-p"
    case faWhatsapp = "fa-whatsapp"
    case faServer = "fa-server"
    case faUserPlus = "fa-user-plus"
    case faUserTimes = "fa-user-times"
    case faBed = "fa-bed"
    case faViacoin = "fa-viacoin"
    case faTrain = "fa-train"
    case faSubway = "fa-subway"
    case faMedium = "fa-medium"
    case faYCombinator = "fa-y-combinator"
    case faOptinMonster = "fa-optin-monster"
    case faOpencart = "fa-opencart"
    case faExpeditedssl = "fa-expeditedssl"
    case faBatteryFull = "fa-battery-full"
    case faBatteryThreeQuarters = "fa-battery-three-quarters"
    case faBatteryHalf = "fa-battery-half"
    case faBatteryQuarter = "fa-battery-quarter"
    case faBatteryEmpty = "fa-battery-empty"
    case faMousePointer = "fa-mouse-pointer"
    case faICursor = "fa-i-cursor"
    case faObjectGroup = "fa-object-group"
    case faObjectUngroup = "fa-object-ungroup"
    case faStickyNote = "fa-sticky-note"
    case faStickyNoteOutlined = "fa-sticky-note-o"
    case faCcJcb = "fa-cc-jcb"
    case faCcDinersClub = "fa-cc-diners-club"
    case faClone = "fa-clone"
    case faBalanceScale = "fa-balance-scale"
    case faHourglassOutlined = "fa-hourglass-o"
    case faHourglassStart = "fa-hourglass-start"
    case faHourglassHalf = "fa-hourglass-half"
    case faHourglassEnd = "fa-hourglass-end"
    case faHourglass = "fa-hourglass"
    case faHandRockOutlined = "fa-hand-rock-o"
    case faHandPaperOutlined = "fa-hand-paper-o"
    case faHandScissorsOutlined = "fa-hand-scissors-o"
    case faHandLizardOutlined = "fa-hand-lizard-o"
    case faHandSpockOutlined = "fa-hand-spock-o"
    case faHandPointerOutlined = "fa-hand-pointer-o"
    case faHandPeaceOutlined = "fa-hand-peace-o"
    case faTrademark = "fa-trademark"
    case faRegistered = "fa-registered"
    case faCreativeCommons = "fa-creative-commons"
    case faGg = "fa-gg"
    case faGgCircle = "fa-gg-circle"
    case faTripadvisor = "fa-tripadvisor"
    case faOdnoklassniki = "fa-odnoklassniki"
    case faOdnoklassnikiSquare = "fa-odnoklassniki-square"
    case faGetPocket = "fa-get-pocket"
    case faWikipediaW = "fa-wikipedia-w"
    case faSafari = "fa-safari"
    case faChrome = "fa-chrome"
    case faFirefox = "fa-firefox"
    case faOpera = "fa-opera"
    case faInternetExplorer = "fa-internet-explorer"
    case faTelevision = "fa-television"
    case faContao = "fa-contao"
    case fa500px = "fa-500px"
    case faAmazon = "fa-amazon"
    case faCalendarPlusOutlined = "fa-calendar-plus-o"
    case faCalendarMinusOutlined = "fa-calendar-minus-o"
    case faCalendarTimesOutlined = "fa-calendar-times-o"
    case faCalendarCheckOutlined = "fa-calendar-check-o"
    case faIndustry = "fa-industry"
    case faMapPin = "fa-map-pin"
    case faMapSigns = "fa-map-signs"
    case faMapOutlined = "fa-map-o"
    case faMap = "fa-map"
    case faCommenting = "fa-commenting"
    case faCommentingOutlined = "fa-commenting-o"
    case faHouzz = "fa-houzz"
    case faVimeo = "fa-vimeo"
    case faBlackTie = "fa-black-tie"
    case faFonticons = "fa-fonticons"
    case faRedditAlien = "fa-reddit-alien"
    case faEdge = "fa-edge"
    case faCreditCardAlt = "fa-credit-card-alt"
    case faCodiepie = "fa-codiepie"
    case faModx = "fa-modx"
    case faFortAwesome = "fa-fort-awesome"
    case faUsb = "fa-usb"
    case faProductHunt = "fa-product-hunt"
    case faMixcloud = "fa-mixcloud"
    case faScribd = "fa-scribd"
    case faPauseCircle = "fa-pause-circle"
    case faPauseCircleOutlined = "fa-pause-circle-o"
    case faStopCircle = "fa-stop-circle"
    case faStopCircleOutlined = "fa-stop-circle-o"
    case faShoppingBag = "fa-shopping-bag"
    case faShoppingBasket = "fa-shopping-basket"
    case faHashtag = "fa-hashtag"
    case faBluetooth = "fa-bluetooth"
    case faBluetoothB = "fa-bluetooth-b"
    case faPercent = "fa-percent"
    case faGitlab = "fa-gitlab"
    case faWpbeginner = "fa-wpbeginner"
    case faWpforms = "fa-wpforms"
    case faEnvira = "fa-envira"
    case faUniversalAccess = "fa-universal-access"
    case faWheelchairAlt = "fa-wheelchair-alt"
    case faQuestionCircleOutlined = "fa-question-circle-o"
    case faBlind = "fa-blind"
    case faAudioDescription = "fa-audio-description"
    case faVolumeControlPhone = "fa-volume-control-phone"
    case faBraille = "fa-braille"
    case faAssistiveListeningSystems = "fa-assistive-listening-systems"
    case faAmericanSignLanguageInterpreting = "fa-american-sign-language-interpreting"
    case faDeaf = "fa-deaf"
    case faGlide = "fa-glide"
    case faGlideG = "fa-glide-g"
    case faSignLanguage = "fa-sign-language"
    case faLowVision = "fa-low-vision"
    case faViadeo = "fa-viadeo"
    case faViadeoSquare = "fa-viadeo-square"
    case faSnapchat = "fa-snapchat"
    case faSnapchatGhost = "fa-snapchat-ghost"
    case faSnapchatSquare = "fa-snapchat-square"
    case faPiedPiper = "fa-pied-piper"
    case faFirstOrder = "fa-first-order"
    case faYoast = "fa-yoast"
    case faThemeisle = "fa-themeisle"
    case faGooglePlusOfficial = "fa-google-plus-official"
    case faFontAwesome = "fa-font-awesome"

    /// Unicode string.
    var unicode: String {
        let value: UInt32
        switch self {
        case .faGlass: value = 0xF000
        case .faMusic: value = 0xF001
        case .faSearch: value = 0xF002
        case .faEnvelopeOutlined: value = 0xF003
        case .faHeart: value = 0xF004
        case .faStar: value = 0xF005
        case .faStarOutlined: value = 0xF006
        case .faUser: value = 0xF007
        case .faFilm: value = 0xF008
        case .faThLarge: value = 0xF009
        case .faTh: value = 0xF00A
        case .faThList: value = 0xF00B
        case .faCheck: value = 0xF00C
        case .faTimes: value = 0xF00D
        case .faSearchPlus: value = 0xF00E
        case .faSearchMinus: value = 0xF010
        case .faPowerOff: value = 0xF011
        case .faSignal: value = 0xF012
        case .faCog: value = 0xF013
        case .faTrashOutlined: value = 0xF014
        case .faHome: value = 0xF015
        case .faFileOutlined: value = 0xF016
        case .faClockOutlined: value = 0xF017
        case .faRoad: value = 0xF018
        case .faDownload: value = 0xF019
        case .faArrowCircleOutlinedDown: value = 0xF01A
        case .faArrowCircleOutlinedUp: value = 0xF01B
        case .faInbox: value = 0xF01C
        case .faPlayCircleOutlined: value = 0xF01D
        case .faRepeat: value = 0xF01E
        case .faRefresh: value = 0xF021
        case .faListAlt: value = 0xF022
        case .faLock: value = 0xF023
        case .faFlag: value = 0xF024
        case .faHeadphones: value = 0xF025
        case .faVolumeOff: value = 0xF026
        case .faVolumeDown: value = 0xF027
        case .faVolumeUp: value = 0xF028
        case .faQrcode: value = 0xF029
        case .faBarcode: value = 0xF02A
        case .faTag: value = 0xF02B
        case .faTags: value = 0xF02C
        case .faBook: value = 0xF02D
        case .faBookmark: value = 0xF02E
        case .faPrint: value = 0xF02F
        case .faCamera: value = 0xF030
        case .faFont: value = 0xF031
        case .faBold: value = 0xF032
        case .faItalic: value = 0xF033
        case .faTextHeight: value = 0xF034
        case .faTextWidth: value = 0xF035
        case .faAlignLeft: value = 0xF036
        case .faAlignCenter: value = 0xF037
        case .faAlignRight: value = 0xF038
        case .faAlignJustify: value = 0xF039
        case .faList: value = 0xF03A
        case .faOutdent: value = 0xF03B
        case .faIndent: value = 0xF03C
        case .faVideoCamera: value = 0xF03D
        case .faPictureOutlined: value = 0xF03E
        case .faPencil: value = 0xF040
        case .faMapMarker: value = 0xF041
        case .faAdjust: value = 0xF042
        case .faTint: value = 0xF043
        case .faPencilSquareOutlined: value = 0xF044
        case .faShareSquareOutlined: value = 0xF045
        case .faCheckSquareOutlined: value = 0xF046
        case .faArrows: value = 0xF047
        case .faStepBackward: value = 0xF048
        case .faFastBackward: value = 0xF049
        case .faBackward: value = 0xF04A
        case .faPlay: value = 0xF04B
        case .faPause: value = 0xF04C
        case .faStop: value = 0xF04D
        case .faForward: value = 0xF04E
        case .faFastForward: value = 0xF050
        case .faStepForward: value = 0xF051
        case .faEject: value = 0xF052
        case .faChevronLeft: value = 0xF053
        case .faChevronRight: value = 0xF054
        case .faPlusCircle: value = 0xF055
        case .faMinusCircle: value = 0xF056
        case .faTimesCircle: value = 0xF057
        case .faCheckCircle: value = 0xF058
        case .faQuestionCircle: value = 0xF059
        case .faInfoCircle: value = 0xF05A
        case .faCrosshairs: value = 0xF05B
        case .faTimesCircleOutlined: value = 0xF05C
        case .faCheckCircleOutlined: value = 0xF05D
        case .faBan: value = 0xF05E
        case .faArrowLeft: value = 0xF060
        case .faArrowRight: value = 0xF061
        case .faArrowUp: value = 0xF062
        case .faArrowDown: value = 0xF063
        case .faShare: value = 0xF064
        case .faExpand: value = 0xF065
        case .faCompress: value = 0xF066
        case .faPlus: value = 0xF067
        case .faMinus: value = 0xF068
        case .faAsterisk: value = 0xF069
        case .faExclamationCircle: value = 0xF06A
        case .faGift: value = 0xF06B
        case .faLeaf: value = 0xF06C
        case .faFire: value = 0xF06D
        case .faEye: value = 0xF06E
        case .faEyeSlash: value = 0xF070
        case .faExclamationTriangle: value = 0xF071
        case .faPlane: value = 0xF072
        case .faCalendar: value = 0xF073
        case .faRandom: value = 0xF074
        case .faComment: value = 0xF075
        case .faMagnet: value = 0xF076
        case .faChevronUp: value = 0xF077
        case .faChevronDown: value = 0xF078
        case .faRetweet: value = 0xF079
        case .faShoppingCart: value = 0xF07A
        case .faFolder: value = 0xF07B
        case .faFolderOpen: value = 0xF07C
        case .faArrowsV: value = 0xF07D
        case .faArrowsH: value = 0xF07E
        case .faBarChart: value = 0xF080
        case .faTwitterSquare: value = 0xF081
        case .faFacebookSquare: value = 0xF082
        case .faCameraRetro: value = 0xF083
        case .faKey: value = 0xF084
        case .faCogs: value = 0xF085
        case .faComments: value = 0xF086
        case .faThumbsOutlinedUp: value = 0xF087
        case .faThumbsOutlinedDown: value = 0xF088
        case .faStarHalf: value = 0xF089
        case .faHeartOutlined: value = 0xF08A
        case .faSignOut: value = 0xF08B
        case .faLinkedinSquare: value = 0xF08C
        case .faThumbTack: value = 0xF08D
        case .faExternalLink: value = 0xF08E
        case .faSignIn: value = 0xF090
        case .faTrophy: value = 0xF091
        case .faGithubSquare: value = 0xF092
        case .faUpload: value = 0xF093
        case .faLemonOutlined: value = 0xF094
        case .faPhone: value = 0xF095
        case .faSquareOutlined: value = 0xF096
        case .faBookmarkOutlined: value = 0xF097
        case .faPhoneSquare: value = 0xF098
        case .faTwitter: value = 0xF099
        case .faFacebook: value = 0xF09A
        case .faGithub: value = 0xF09B
        case .faUnlock: value = 0xF09C
        case .faCreditCard: value = 0xF09D
        case .faRss: value = 0xF09E
        case .faHddOutlined: value = 0xF0A0
        case .faBullhorn: value = 0xF0A1
        case .faBell: value = 0xF0F3
        case .faCertificate: value = 0xF0A3
        case .faHandOutlinedRight: value = 0xF0A4
        case .faHandOutlinedLeft: value = 0xF0A5
        case .faHandOutlinedUp: value = 0xF0A6
        case .faHandOutlinedDown: value = 0xF0A7
        case .faArrowCircleLeft: value = 0xF0A8
        case .faArrowCircleRight: value = 0xF0A9
        case .faArrowCircleUp: value = 0xF0Aa
        case .faArrowCircleDown: value = 0xF0Ab
        case .faGlobe: value = 0xF0Ac
        case .faWrench: value = 0xF0Ad
        case .faTasks: value = 0xF0Ae
        case .faFilter: value = 0xF0B0
        case .faBriefcase: value = 0xF0B1
        case .faArrowsAlt: value = 0xF0B2
        case .faUsers: value = 0xF0C0
        case .faLink: value = 0xF0C1
        case .faCloud: value = 0xF0C2
        case .faFlask: value = 0xF0C3
        case .faScissors: value = 0xF0C4
        case .faFilesOutlined: value = 0xF0C5
        case .faPaperclip: value = 0xF0C6
        case .faFloppyOutlined: value = 0xF0C7
        case .faSquare: value = 0xF0C8
        case .faBars: value = 0xF0C9
        case .faListUl: value = 0xF0Ca
        case .faListOl: value = 0xF0Cb
        case .faStrikethrough: value = 0xF0Cc
        case .faUnderline: value = 0xF0Cd
        case .faTable: value = 0xF0Ce
        case .faMagic: value = 0xF0D0
        case .faTruck: value = 0xF0D1
        case .faPinterest: value = 0xF0D2
        case .faPinterestSquare: value = 0xF0D3
        case .faGooglePlusSquare: value = 0xF0D4
        case .faGooglePlus: value = 0xF0D5
        case .faMoney: value = 0xF0D6
        case .faCaretDown: value = 0xF0D7
        case .faCaretUp: value = 0xF0D8
        case .faCaretLeft: value = 0xF0D9
        case .faCaretRight: value = 0xF0Da
        case .faColumns: value = 0xF0Db
        case .faSort: value = 0xF0Dc
        case .faSortDesc: value = 0xF0Dd
        case .faSortAsc: value = 0xF0De
        case .faEnvelope: value = 0xF0E0
        case .faLinkedin: value = 0xF0E1
        case .faUndo: value = 0xF0E2
        case .faGavel: value = 0xF0E3
        case .faTachometer: value = 0xF0E4
        case .faCommentOutlined: value = 0xF0E5
        case .faCommentsOutlined: value = 0xF0E6
        case .faBolt: value = 0xF0E7
        case .faSitemap: value = 0xF0E8
        case .faUmbrella: value = 0xF0E9
        case .faClipboard: value = 0xF0Ea
        case .faLightbulbOutlined: value = 0xF0Eb
        case .faExchange: value = 0xF0Ec
        case .faCloudDownload: value = 0xF0Ed
        case .faCloudUpload: value = 0xF0Ee
        case .faUserMd: value = 0xF0F0
        case .faStethoscope: value = 0xF0F1
        case .faSuitcase: value = 0xF0F2
        case .faBellOutlined: value = 0xF0A2
        case .faCoffee: value = 0xF0F4
        case .faCutlery: value = 0xF0F5
        case .faFileTextOutlined: value = 0xF0F6
        case .faBuildingOutlined: value = 0xF0F7
        case .faHospitalOutlined: value = 0xF0F8
        case .faAmbulance: value = 0xF0F9
        case .faMedkit: value = 0xF0Fa
        case .faFighterJet: value = 0xF0Fb
        case .faBeer: value = 0xF0Fc
        case .faHSquare: value = 0xF0Fd
        case .faPlusSquare: value = 0xF0Fe
        case .faAngleDoubleLeft: value = 0xF100
        case .faAngleDoubleRight: value = 0xF101
        case .faAngleDoubleUp: value = 0xF102
        case .faAngleDoubleDown: value = 0xF103
        case .faAngleLeft: value = 0xF104
        case .faAngleRight: value = 0xF105
        case .faAngleUp: value = 0xF106
        case .faAngleDown: value = 0xF107
        case .faDesktop: value = 0xF108
        case .faLaptop: value = 0xF109
        case .faTablet: value = 0xF10A
        case .faMobile: value = 0xF10B
        case .faCircleOutlined: value = 0xF10C
        case .faQuoteLeft: value = 0xF10D
        case .faQuoteRight: value = 0xF10E
        case .faSpinner: value = 0xF110
        case .faCircle: value = 0xF111
        case .faReply: value = 0xF112
        case .faGithubAlt: value = 0xF113
        case .faFolderOutlined: value = 0xF114
        case .faFolderOpenOutlined: value = 0xF115
        case .faSmileOutlined: value = 0xF118
        case .faFrownOutlined: value = 0xF119
        case .faMehOutlined: value = 0xF11A
        case .faGamepad: value = 0xF11B
        case .faKeyboardOutlined: value = 0xF11C
        case .faFlagOutlined: value = 0xF11D
        case .faFlagCheckered: value = 0xF11E
        case .faTerminal: value = 0xF120
        case .faCode: value = 0xF121
        case .faReplyAll: value = 0xF122
        case .faStarHalfOutlined: value = 0xF123
        case .faLocationArrow: value = 0xF124
        case .faCrop: value = 0xF125
        case .faCodeFork: value = 0xF126
        case .faChainBroken: value = 0xF127
        case .faQuestion: value = 0xF128
        case .faInfo: value = 0xF129
        case .faExclamation: value = 0xF12A
        case .faSuperscript: value = 0xF12B
        case .faSubscript: value = 0xF12C
        case .faEraser: value = 0xF12D
        case .faPuzzlePiece: value = 0xF12E
        case .faMicrophone: value = 0xF130
        case .faMicrophoneSlash: value = 0xF131
        case .faShield: value = 0xF132
        case .faCalendarOutlined: value = 0xF133
        case .faFireExtinguisher: value = 0xF134
        case .faRocket: value = 0xF135
        case .faMaxcdn: value = 0xF136
        case .faChevronCircleLeft: value = 0xF137
        case .faChevronCircleRight: value = 0xF138
        case .faChevronCircleUp: value = 0xF139
        case .faChevronCircleDown: value = 0xF13A
        case .faHtml5: value = 0xF13B
        case .faCss3: value = 0xF13C
        case .faAnchor: value = 0xF13D
        case .faUnlockAlt: value = 0xF13E
        case .faBullseye: value = 0xF140
        case .faEllipsisH: value = 0xF141
        case .faEllipsisV: value = 0xF142
        case .faRssSquare: value = 0xF143
        case .faPlayCircle: value = 0xF144
        case .faTicket: value = 0xF145
        case .faMinusSquare: value = 0xF146
        case .faMinusSquareOutlined: value = 0xF147
        case .faLevelUp: value = 0xF148
        case .faLevelDown: value = 0xF149
        case .faCheckSquare: value = 0xF14A
        case .faPencilSquare: value = 0xF14B
        case .faExternalLinkSquare: value = 0xF14C
        case .faShareSquare: value = 0xF14D
        case .faCompass: value = 0xF14E
        case .faCaretSquareOutlinedDown: value = 0xF150
        case .faCaretSquareOutlinedUp: value = 0xF151
        case .faCaretSquareOutlinedRight: value = 0xF152
        case .faEur: value = 0xF153
        case .faGbp: value = 0xF154
        case .faUsd: value = 0xF155
        case .faInr: value = 0xF156
        case .faJpy: value = 0xF157
        case .faRub: value = 0xF158
        case .faKrw: value = 0xF159
        case .faBtc: value = 0xF15A
        case .faFile: value = 0xF15B
        case .faFileText: value = 0xF15C
        case .faSortAlphaAsc: value = 0xF15D
        case .faSortAlphaDesc: value = 0xF15E
        case .faSortAmountAsc: value = 0xF160
        case .faSortAmountDesc: value = 0xF161
        case .faSortNumericAsc: value = 0xF162
        case .faSortNumericDesc: value = 0xF163
        case .faThumbsUp: value = 0xF164
        case .faThumbsDown: value = 0xF165
        case .faYoutubeSquare: value = 0xF166
        case .faYoutube: value = 0xF167
        case .faXing: value = 0xF168
        case .faXingSquare: value = 0xF169
        case .faYoutubePlay: value = 0xF16A
        case .faDropbox: value = 0xF16B
        case .faStackOverflow: value = 0xF16C
        case .faInstagram: value = 0xF16D
        case .faFlickr: value = 0xF16E
        case .faAdn: value = 0xF170
        case .faBitbucket: value = 0xF171
        case .faBitbucketSquare: value = 0xF172
        case .faTumblr: value = 0xF173
        case .faTumblrSquare: value = 0xF174
        case .faLongArrowDown: value = 0xF175
        case .faLongArrowUp: value = 0xF176
        case .faLongArrowLeft: value = 0xF177
        case .faLongArrowRight: value = 0xF178
        case .faApple: value = 0xF179
        case .faWindows: value = 0xF17A
        case .faAndroid: value = 0xF17B
        case .faLinux: value = 0xF17C
        case .faDribbble: value = 0xF17D
        case .faSkype: value = 0xF17E
        case .faFoursquare: value = 0xF180
        case .faTrello: value = 0xF181
        case .faFemale: value = 0xF182
        case .faMale: value = 0xF183
        case .faGratipay: value = 0xF184
        case .faSunOutlined: value = 0xF185
        case .faMoonOutlined: value = 0xF186
        case .faArchive: value = 0xF187
        case .faBug: value = 0xF188
        case .faVk: value = 0xF189
        case .faWeibo: value = 0xF18A
        case .faRenren: value = 0xF18B
        case .faPagelines: value = 0xF18C
        case .faStackExchange: value = 0xF18D
        case .faArrowCircleOutlinedRight: value = 0xF18E
        case .faArrowCircleOutlinedLeft: value = 0xF190
        case .faCaretSquareOutlinedLeft: value = 0xF191
        case .faDotCircleOutlined: value = 0xF192
        case .faWheelchair: value = 0xF193
        case .faVimeoSquare: value = 0xF194
        case .faTry: value = 0xF195
        case .faPlusSquareOutlined: value = 0xF196
        case .faSpaceShuttle: value = 0xF197
        case .faSlack: value = 0xF198
        case .faEnvelopeSquare: value = 0xF199
        case .faWordpress: value = 0xF19A
        case .faOpenid: value = 0xF19B
        case .faUniversity: value = 0xF19C
        case .faGraduationCap: value = 0xF19D
        case .faYahoo: value = 0xF19E
        case .faGoogle: value = 0xF1A0
        case .faReddit: value = 0xF1A1
        case .faRedditSquare: value = 0xF1A2
        case .faStumbleuponCircle: value = 0xF1A3
        case .faStumbleupon: value = 0xF1A4
        case .faDelicious: value = 0xF1A5
        case .faDigg: value = 0xF1A6
        case .faPiedPiperPp: value = 0xF1A7
        case .faPiedPiperAlt: value = 0xF1A8
        case .faDrupal: value = 0xF1A9
        case .faJoomla: value = 0xF1Aa
        case .faLanguage: value = 0xF1Ab
        case .faFax: value = 0xF1Ac
        case .faBuilding: value = 0xF1Ad
        case .faChild: value = 0xF1Ae
        case .faPaw: value = 0xF1B0
        case .faSpoon: value = 0xF1B1
        case .faCube: value = 0xF1B2
        case .faCubes: value = 0xF1B3
        case .faBehance: value = 0xF1B4
        case .faBehanceSquare: value = 0xF1B5
        case .faSteam: value = 0xF1B6
        case .faSteamSquare: value = 0xF1B7
        case .faRecycle: value = 0xF1B8
        case .faCar: value = 0xF1B9
        case .faTaxi: value = 0xF1Ba
        case .faTree: value = 0xF1Bb
        case .faSpotify: value = 0xF1Bc
        case .faDeviantart: value = 0xF1Bd
        case .faSoundcloud: value = 0xF1Be
        case .faDatabase: value = 0xF1C0
        case .faFilePdfOutlined: value = 0xF1C1
        case .faFileWordOutlined: value = 0xF1C2
        case .faFileExcelOutlined: value = 0xF1C3
        case .faFilePowerpointOutlined: value = 0xF1C4
        case .faFileImageOutlined: value = 0xF1C5
        case .faFileArchiveOutlined: value = 0xF1C6
        case .faFileAudioOutlined: value = 0xF1C7
        case .faFileVideoOutlined: value = 0xF1C8
        case .faFileCodeOutlined: value = 0xF1C9
        case .faVine: value = 0xF1Ca
        case .faCodepen: value = 0xF1Cb
        case .faJsfiddle: value = 0xF1Cc
        case .faLifeRing: value = 0xF1Cd
        case .faCircleOutlinedNotch: value = 0xF1Ce
        case .faRebel: value = 0xF1D0
        case .faEmpire: value = 0xF1D1
        case .faGitSquare: value = 0xF1D2
        case .faGit: value = 0xF1D3
        case .faHackerNews: value = 0xF1D4
        case .faTencentWeibo: value = 0xF1D5
        case .faQq: value = 0xF1D6
        case .faWeixin: value = 0xF1D7
        case .faPaperPlane: value = 0xF1D8
        case .faPaperPlaneOutlined: value = 0xF1D9
        case .faHistory: value = 0xF1Da
        case .faCircleThin: value = 0xF1Db
        case .faHeader: value = 0xF1Dc
        case .faParagraph: value = 0xF1Dd
        case .faSliders: value = 0xF1De
        case .faShareAlt: value = 0xF1E0
        case .faShareAltSquare: value = 0xF1E1
        case .faBomb: value = 0xF1E2
        case .faFutbolOutlined: value = 0xF1E3
        case .faTty: value = 0xF1E4
        case .faBinoculars: value = 0xF1E5
        case .faPlug: value = 0xF1E6
        case .faSlideshare: value = 0xF1E7
        case .faTwitch: value = 0xF1E8
        case .faYelp: value = 0xF1E9
        case .faNewspaperOutlined: value = 0xF1Ea
        case .faWifi: value = 0xF1Eb
        case .faCalculator: value = 0xF1Ec
        case .faPaypal: value = 0xF1Ed
        case .faGoogleWallet: value = 0xF1Ee
        case .faCcVisa: value = 0xF1F0
        case .faCcMastercard: value = 0xF1F1
        case .faCcDiscover: value = 0xF1F2
        case .faCcAmex: value = 0xF1F3
        case .faCcPaypal: value = 0xF1F4
        case .faCcStripe: value = 0xF1F5
        case .faBellSlash: value = 0xF1F6
        case .faBellSlashOutlined: value = 0xF1F7
        case .faTrash: value = 0xF1F8
        case .faCopyright: value = 0xF1F9
        case .faAt: value = 0xF1Fa
        case .faEyedropper: value = 0xF1Fb
        case .faPaintBrush: value = 0xF1Fc
        case .faBirthdayCake: value = 0xF1Fd
        case .faAreaChart: value = 0xF1Fe
        case .faPieChart: value = 0xF200
        case .faLineChart: value = 0xF201
        case .faLastfm: value = 0xF202
        case .faLastfmSquare: value = 0xF203
        case .faToggleOff: value = 0xF204
        case .faToggleOn: value = 0xF205
        case .faBicycle: value = 0xF206
        case .faBus: value = 0xF207
        case .faIoxhost: value = 0xF208
        case .faAngellist: value = 0xF209
        case .faCc: value = 0xF20A
        case .faIls: value = 0xF20B
        case .faMeanpath: value = 0xF20C
        case .faBuysellads: value = 0xF20D
        case .faConnectdevelop: value = 0xF20E
        case .faDashcube: value = 0xF210
        case .faForumbee: value = 0xF211
        case .faLeanpub: value = 0xF212
        case .faSellsy: value = 0xF213
        case .faShirtsinbulk: value = 0xF214
        case .faSimplybuilt: value = 0xF215
        case .faSkyatlas: value = 0xF216
        case .faCartPlus: value = 0xF217
        case .faCartArrowDown: value = 0xF218
        case .faDiamond: value = 0xF219
        case .faShip: value = 0xF21A
        case .faUserSecret: value = 0xF21B
        case .faMotorcycle: value = 0xF21C
        case .faStreetView: value = 0xF21D
        case .faHeartbeat: value = 0xF21E
        case .faVenus: value = 0xF221
        case .faMars: value = 0xF222
        case .faMercury: value = 0xF223
        case .faTransgender: value = 0xF224
        case .faTransgenderAlt: value = 0xF225
        case .faVenusDouble: value = 0xF226
        case .faMarsDouble: value = 0xF227
        case .faVenusMars: value = 0xF228
        case .faMarsStroke: value = 0xF229
        case .faMarsStrokeV: value = 0xF22A
        case .faMarsStrokeH: value = 0xF22B
        case .faNeuter: value = 0xF22C
        case .faGenderless: value = 0xF22D
        case .faFacebookOfficial: value = 0xF230
        case .faPinterestP: value = 0xF231
        case .faWhatsapp: value = 0xF232
        case .faServer: value = 0xF233
        case .faUserPlus: value = 0xF234
        case .faUserTimes: value = 0xF235
        case .faBed: value = 0xF236
        case .faViacoin: value = 0xF237
        case .faTrain: value = 0xF238
        case .faSubway: value = 0xF239
        case .faMedium: value = 0xF23A
        case .faYCombinator: value = 0xF23B
        case .faOptinMonster: value = 0xF23C
        case .faOpencart: value = 0xF23D
        case .faExpeditedssl: value = 0xF23E
        case .faBatteryFull: value = 0xF240
        case .faBatteryThreeQuarters: value = 0xF241
        case .faBatteryHalf: value = 0xF242
        case .faBatteryQuarter: value = 0xF243
        case .faBatteryEmpty: value = 0xF244
        case .faMousePointer: value = 0xF245
        case .faICursor: value = 0xF246
        case .faObjectGroup: value = 0xF247
        case .faObjectUngroup: value = 0xF248
        case .faStickyNote: value = 0xF249
        case .faStickyNoteOutlined: value = 0xF24A
        case .faCcJcb: value = 0xF24B
        case .faCcDinersClub: value = 0xF24C
        case .faClone: value = 0xF24D
        case .faBalanceScale: value = 0xF24E
        case .faHourglassOutlined: value = 0xF250
        case .faHourglassStart: value = 0xF251
        case .faHourglassHalf: value = 0xF252
        case .faHourglassEnd: value = 0xF253
        case .faHourglass: value = 0xF254
        case .faHandRockOutlined: value = 0xF255
        case .faHandPaperOutlined: value = 0xF256
        case .faHandScissorsOutlined: value = 0xF257
        case .faHandLizardOutlined: value = 0xF258
        case .faHandSpockOutlined: value = 0xF259
        case .faHandPointerOutlined: value = 0xF25A
        case .faHandPeaceOutlined: value = 0xF25B
        case .faTrademark: value = 0xF25C
        case .faRegistered: value = 0xF25D
        case .faCreativeCommons: value = 0xF25E
        case .faGg: value = 0xF260
        case .faGgCircle: value = 0xF261
        case .faTripadvisor: value = 0xF262
        case .faOdnoklassniki: value = 0xF263
        case .faOdnoklassnikiSquare: value = 0xF264
        case .faGetPocket: value = 0xF265
        case .faWikipediaW: value = 0xF266
        case .faSafari: value = 0xF267
        case .faChrome: value = 0xF268
        case .faFirefox: value = 0xF269
        case .faOpera: value = 0xF26A
        case .faInternetExplorer: value = 0xF26B
        case .faTelevision: value = 0xF26C
        case .faContao: value = 0xF26D
        case .fa500px: value = 0xF26E
        case .faAmazon: value = 0xF270
        case .faCalendarPlusOutlined: value = 0xF271
        case .faCalendarMinusOutlined: value = 0xF272
        case .faCalendarTimesOutlined: value = 0xF273
        case .faCalendarCheckOutlined: value = 0xF274
        case .faIndustry: value = 0xF275
        case .faMapPin: value = 0xF276
        case .faMapSigns: value = 0xF277
        case .faMapOutlined: value = 0xF278
        case .faMap: value = 0xF279
        case .faCommenting: value = 0xF27A
        case .faCommentingOutlined: value = 0xF27B
        case .faHouzz: value = 0xF27C
        case .faVimeo: value = 0xF27D
        case .faBlackTie: value = 0xF27E
        case .faFonticons: value = 0xF280
        case .faRedditAlien: value = 0xF281
        case .faEdge: value = 0xF282
        case .faCreditCardAlt: value = 0xF283
        case .faCodiepie: value = 0xF284
        case .faModx: value = 0xF285
        case .faFortAwesome: value = 0xF286
        case .faUsb: value = 0xF287
        case .faProductHunt: value = 0xF288
        case .faMixcloud: value = 0xF289
        case .faScribd: value = 0xF28A
        case .faPauseCircle: value = 0xF28B
        case .faPauseCircleOutlined: value = 0xF28C
        case .faStopCircle: value = 0xF28D
        case .faStopCircleOutlined: value = 0xF28E
        case .faShoppingBag: value = 0xF290
        case .faShoppingBasket: value = 0xF291
        case .faHashtag: value = 0xF292
        case .faBluetooth: value = 0xF293
        case .faBluetoothB: value = 0xF294
        case .faPercent: value = 0xF295
        case .faGitlab: value = 0xF296
        case .faWpbeginner: value = 0xF297
        case .faWpforms: value = 0xF298
        case .faEnvira: value = 0xF299
        case .faUniversalAccess: value = 0xF29A
        case .faWheelchairAlt: value = 0xF29B
        case .faQuestionCircleOutlined: value = 0xF29C
        case .faBlind: value = 0xF29D
        case .faAudioDescription: value = 0xF29E
        case .faVolumeControlPhone: value = 0xF2A0
        case .faBraille: value = 0xF2A1
        case .faAssistiveListeningSystems: value = 0xF2A2
        case .faAmericanSignLanguageInterpreting: value = 0xF2A3
        case .faDeaf: value = 0xF2A4
        case .faGlide: value = 0xF2A5
        case .faGlideG: value = 0xF2A6
        case .faSignLanguage: value = 0xF2A7
        case .faLowVision: value = 0xF2A8
        case .faViadeo: value = 0xF2A9
        case .faViadeoSquare: value = 0xF2Aa
        case .faSnapchat: value = 0xF2Ab
        case .faSnapchatGhost: value = 0xF2Ac
        case .faSnapchatSquare: value = 0xF2Ad
        case .faPiedPiper: value = 0xF2Ae
        case .faFirstOrder: value = 0xF2B0
        case .faYoast: value = 0xF2B1
        case .faThemeisle: value = 0xF2B2
        case .faGooglePlusOfficial: value = 0xF2B3
        case .faFontAwesome: value = 0xF2B4
        }
        return String(UnicodeScalar(value))
    }
}
